sudo: false

language: php

php:
    - 7.1
    - 7.2
    - nightly

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - SYMFONY_VERSION=^2.8
    - SYMFONY_VERSION=^3.0
    - SYMFONY_VERSION=^4.0
    - COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=^2.8 COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=^3.0 COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=^4.0 COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=dev-master

matrix:
    fast_finish: true

    allow_failures:
        - php: nightly
        - env: SYMFONY_VERSION=dev-master

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors
